services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis-data:/usr/local/etc/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  server:
    container_name: server
    depends_on:
      - redis
    ports:
      - 3333:3333
    build:  
      context: ./packages/server
    env_file:
      - .env
        
  
  next-app:
    container_name: next-app
    depends_on:
      - server
    ports:
      - 3000:3000
    build:
      context: ./packages/web
      args:
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    environment:
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}